### ISSUE TITLE
Rollout on descriptions opens 'downwards' pushing description off screen

### ISSUE THREAD

**Issue by andybloke** [remigiilli/dw#13]
When clicking on a thing, the description opens downwards. If said thing is at the bottom of the screen it forces the user to scroll down to read it. Can it push up instead?

Firefox Quantum (57)
windows 7

**Comment by remigiilli** [comment]
@andybloke i cant reproduce it on Firefox under linux. Can you provide a link where this happens and the resolution you are using?

**Comment by andybloke** [comment]
1920*1080
http://dw.knoblau.ch/skills
For me Common Lore Imperial Creed is at the bottom of the screen. Clicking that, I cant even see that something opened because it opened off screen. But the effect is the same for all the skills at the bottom.
http://dw.knoblau.ch/skills#skill-36
Screenshot: https://screenshots.firefox.com/ErXCT87mQJSDsxDA/dw.knoblau.ch
